// Code generated by ent, DO NOT EDIT.

package ent

import (
	"mobility-server/ent/customer"
	"mobility-server/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	customerFields := schema.Customer{}.Fields()
	_ = customerFields
	// customerDescCreatedAt is the schema descriptor for created_at field.
	customerDescCreatedAt := customerFields[1].Descriptor()
	// customer.DefaultCreatedAt holds the default value on creation for the created_at field.
	customer.DefaultCreatedAt = customerDescCreatedAt.Default.(time.Time)
	// customerDescFirstName is the schema descriptor for first_name field.
	customerDescFirstName := customerFields[4].Descriptor()
	// customer.DefaultFirstName holds the default value on creation for the first_name field.
	customer.DefaultFirstName = customerDescFirstName.Default.(string)
	// customerDescIsNew is the schema descriptor for is_new field.
	customerDescIsNew := customerFields[8].Descriptor()
	// customer.DefaultIsNew holds the default value on creation for the is_new field.
	customer.DefaultIsNew = customerDescIsNew.Default.(bool)
	// customerDescID is the schema descriptor for id field.
	customerDescID := customerFields[0].Descriptor()
	// customer.DefaultID holds the default value on creation for the id field.
	customer.DefaultID = customerDescID.Default.(func() uuid.UUID)
}
